### ISSUE TITLE
Setting yicesEnableMCSat doesn't enable the nonlinear arithmetic feature

### ISSUE THREAD

**Issue by atomb** [GaloisInc/what4#133]
When using the online Yices solver (through `yicesStartSolver` or the `OnlineSolver` class), setting the `yicesEnableMCSat` option does cause the solver to be started with the `--mcsat` flag, but it does not configure the connection to enable the nonlinear arithmetic feature.

This can be demonstrated using Crux by running `crux-llvm -s yices --mcsat simple-nonlinear.c` where `simple-nonlinear.c` contains:

```` c
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#include "crucible.h"

int main() {

    float a = crucible_float("a");
    float b = crucible_float("b");
    float c = crucible_float("c");
    
    assuming(a > 0.0);
    assuming(a < 2.0);
    assuming(b > 0.0);
    assuming(b < 5.0);
    
    c = a*b; 

    check(c < 10.0); 
   
    return 0;
}
````

A spot fix for this issue is easy (checking the existing `enableMCSat` boolean in `startYicesSolver`, and adding `useNonlinearArithmetic` to `features` if it's set), but that could add cruft to an already somewhat complex collection of feature identification logic that's spread over multiple functions. Is there some refactoring we should do?

**Comment by robdockins** [comment]
I think the spot fix is worth doing for now, but I agree that this logic is complicated and we should rethink what we want from it.

The main complication is exactly this one with yices.  The problem is basically that there are two different solvers living in the same executable and neither one subsumes the other.  The "classic" yices doesn't support nonlinear arithmetic, and the "MCMT" yices has limited theory support.

One way we might handle this is by making this choice more obvious and treating normal "yices" and "yices-nl" as different solvers the user must chose between.  Then, a lot of the complicated feature discovery stuff gets a lot simpler.  I don't think this issue arises nearly as much for other solvers, which usually have a good default "enable everything" logic that we use.
