### ISSUE TITLE
Test failures with Boolector 3.2.2

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/what4#145]
The `adapter-test` succeeds with Boolector 3.2.1, but fails with version 3.2.2.  It is not clear yet what is causing this.

**Comment by RyanGlScott** [comment]
I think this is due to Boolector 3.2.2 [removing the `--smt2-model` option](https://github.com/Boolector/boolector/commit/2bde574a1467fb61f79caea388256445d9ef5312) in favor of `--output-format=smt2`. Currently, `what4` passes both options to Boolector. Here is what happens when `what4` invokes Boolector 3.2.2 with `--smt2-model` in `adapter-test`:

```
$ ~/Software/boolector-3.2.2/build/bin/boolector --smt2 --smt2-model --incremental --output-format=smt2 -e=0
boolector: invalid option '--smt2-model'
```

If I remove `--smt2-model` from [this line](https://github.com/GaloisInc/what4/blob/d4517282f2f55b2fc06e71d9105a22e232bba23b/what4/src/What4/Solver/Boolector.hs#L128), then `adapter-test` succeeds with both Boolector 3.2.1 and 3.2.2.

**Comment by robdockins** [comment]
Sounds like a pretty easy fix then, nice.
