### ISSUE TITLE
New deprecation warning

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/what4#195]
I don't remember seeing this one before.  I'm not sure what the correct mitigation is yet.

```
test/ExprBuilderSMTLib2.hs:1115:3: warning: [-Wdeprecations]
    In the use of ‘testProperty’ (imported from Test.Tasty.Hedgehog):
    Deprecated: "testProperty will cause Hedgehog to provide incorrect instructions for re-checking properties"
     |
1115 |   testProperty ("test resolveSymBV (" ++ show (PP.pretty searchStrat) ++ ")") $
     |   ^^^^^^^^^^^^

```

**Comment by RyanGlScott** [comment]
This is a new warning introduced in `tasty-hedgehog-1.2.0.0`. See https://github.com/qfpl/tasty-hedgehog/pull/42. Unfortunately, this affects pretty much every test suite we have that uses `tasty-hedgehog`.

**Comment by RyanGlScott** [comment]
If we decide it's not worth it to migrate every use of `testProperty` to `testPropertyName`, we could just punt and define our own version of `testProperty` without the deprecation warning. Something like this, perhaps:

```hs
import qualified Data.String

testProperty' :: TestName -> Property -> TestTree
testProperty' name = testPropertyNamed name (Data.String.fromString name)
```

**Comment by RyanGlScott** [comment]
As an experiment, I decided how awful it would be to convert all `hedgehog` properties in `parameterized-utils` to top-level values so that they could be used with `testPropertyNamed`. See GaloisInc/parameterized-utils#131 for the results. Unsurprisingly, this was an extremely tedious process. Mechanical, but tedious.

`what4` has even _more_ properties than `parameterized-utils`, so I ultimately ran out of energy to apply the same treatment to `what4`. I've compromised by defining our own, warning-free version of `testProperty` in #198 and using that everywhere.
