### ISSUE TITLE
Bugs in BVDomain `sdiv` and `srem`

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/what4#28]
While adding QuickCheck properties to the BVDomain code, mirroring the Cryptol properties in the specification, I discovered that `sdiv` and `srem` do not meet their specs.

From the Cryptol specification:
```
arithdomain> :set base=10
arithdomain> let a = interval`{6} 6 9
arithdomain> let b = interval`{6} 36 33
arithdomain> a
{lo = 6, sz = 9}
arithdomain> b
{lo = 36, sz = 33}
arithdomain> sdiv a b
{lo = 49, sz = 30}
```

From the Haskell:
```
> let a = range (knownNat :: NatRepr 6) 6 (6+9)
> let b = range (knownNat :: NatRepr 6) 36 (36+33)
> a
BVDInterval 63 6 9
> b
BVDInterval 63 36 33
> sdiv (knownNat :: NatRepr 6) a b
BVDInterval 63 0 3
```

There are counterexamples for `srem` as well, but I haven't found any this small.  I'm guessing the bugs are related, and have something to do with emulating bitvectors using integers; but it isn't obvious.

@brianhuffman, any ideas?

**Comment by brianhuffman** [comment]
I'm looking into it now.

**Comment by brianhuffman** [comment]
It looks like the function `rbounds` in `BVDomain.hs` was implemented all wrong, in that it was choosing the wrong mod-2^n representatives of the interval endpoints. This was probably due to how the Cryptol `rbounds` was documented in a kind of misleading way. I'm fixing both the Haskell implementation and the Cryptol docstring to make more sense.

There was also a second bug that looks like a typo, where `sdiv` was calling `sbounds` where it should have been calling `rbounds`. I am adding a new type to distinguish the two different interpretations of `(Integer, Integer)` in the code, which will prevent that particular mistake.

I should have a patch ready pretty soon.
