### ISSUE TITLE
Improve documentation regarding partial functions

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/what4#72]
The haddock documentation for `What4.Interface.intDiv` says that it satisfies the spec `x * (div x y) + (mod x y) == x`. This should instead say that `y * (div x y) + (mod x y) == x`.

https://github.com/GaloisInc/what4/blob/2d8e5359677a1bac5950803fe4375f98f11a9bf1/what4/src/What4/Interface.hs#L604

The statement "The value of @intDiv x y@ is undefined when @y = 0@" could also use more explanation. What kind of undefinedness is this? I believe it means that the function doesn't cause an error or an exception when `y = 0`, just that its return value is unspecified/undetermined.

The same docstring has an ill-formatted bulleted list at the end; we should fix this as well.

**Comment by benjaminselfridge** [comment]
https://github.com/GaloisInc/what4/pull/74

**Comment by robdockins** [comment]
I'll copy my comments regarding partial functions from the above PR here:

Regarding the documentation and error behavior, I'm starting to think we should do the following: partial functions are always "unspecified" in the sense that SMTLib uses it (the results are treated as uninterpreted). Such functions get "stuck" when evaluating instead of throwing errors, which means they will not constant fold and ground evaluation will query the solver instead of computing.

**Comment by robdockins** [comment]
Closed via #97
